debug = true
port = 6041
logLevel = "debug"

[ssl]
enable = false
certFile = ""
keyFile = ""

[log]
path = "/var/log/taos"
rotationCount = 30
rotationTime = "24h"

[opentsdb]
enable = true

[influxdb]
enable = true

[collectd]
enable = true
port = 25826
db = "collectd"
user = "root"
password = "taosdata"
worker = 10

[statsd]
enable = true
port = 8125
db = "statsd"
user = "root"
password = "taosdata"
worker = 10
gatherInterval = "20s"
protocol = "udp"
maxTCPConnections = 250
tcpKeepAlive = false
allowPendingMessages = 10000
deleteCounters = true
deleteGauges = true
deleteSets = true
deleteTimings = true