name: Go

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: 'blm3'
      - name: checkout TDengine
        uses: actions/checkout@v2
        with:
          repository: 'taosdata/TDengine'
          path: 'TDengine'
          ref: 'develop'
      - name: install build-essential
        run: apt-get update && apt-get install -y build-essential curl gcc cmake

      - name: install TDengine
        run: cd TDengine && mkdir debug && cd debug && cmake .. -DBUILD_HTTP=true -DBUILD_JDBC=false && make && make install

      - name: start taosd
        run: nohup sudo taosd &

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Test
        run: cd ./blm3 && go test -v ./...
